### PR TITLE
🩹 Fix showKeyboard and Typo

### PR DESCRIPTION
**Pull request by Wz-FiveM**

### CODE REVIEW

**Comment by MoskalykA** [comment]
Have you tested your code? https://github.com/NextCitizens/ncs_core/pull/55

**Comment by Wz-FiveM** [comment]
Of course, that's why I'm going for a PR

**Comment by MoskalykA** [comment]
image

**Comment by v4mmpp** [comment]
the code is already good why change it?

**Comment by MoskalykA** [comment]
> 

Especially since with this pr, it no longer works properly

**Comment by MoskalykA** [comment]
> the code is already good why change it?

Especially since with this pr, it no longer works properly

**Comment by Wz-FiveM** [comment]
the function don't return value

**Comment by MoskalykA** [comment]
> the function don't return value

What do you mean?

**Comment by Wz-FiveM** [comment]
After entering a value in the showBox the code returns nothing

**Comment by Wz-FiveM** [comment]
image

**Comment by Wz-FiveM** [comment]
> image

You can't use a showBox outside of a thread or function it's normal

**Comment by Wz-FiveM** [comment]
image

**Comment by MoskalykA** [comment]
I had not taken this into account but I opened a pr with a pragmatic syntax https://github.com/NextCitizens/ncs_core/pull/65

**Comment by Wz-FiveM** [comment]
No problem, I close my PR to leave that yours

**Pull request closed without merging**
