### PR TITLE
🩹 Fix showKeyboard.

### PR DESCRIPTION
**Pull request by MoskalykA**

### CODE REVIEW

**Comment by Wz-FiveM** [comment]
It works perfectly.

**Comment by PABLO-1610** [comment]
> It works perfectly.

What ? This code or the previous one ?

**Comment by Wz-FiveM** [comment]
> > It works perfectly.
> 
> What ? This code or the previous one ?

This code

**Comment by PABLO-1610** [comment]
> > > It works perfectly.
> > 
> > 
> > What ? This code or the previous one ?
> 
> This code

So FiveM Lua is implementing promise 🤔 ?

**Comment by MoskalykA** [comment]
> Member

yes, https://github.com/citizenfx/fivem/blob/master/data/shared/citizen/scripting/lua/deferred.lua

**Comment by PABLO-1610** [comment]
> Contributor

Lmao awesome

**Comment by PABLO-1610** [comment]
That's why I love OpenSource ❤️

**Review by PABLO-1610 — APPROVED** [review]

**Pull request merged**
