### PR TITLE
✨ Npc system

### PR DESCRIPTION
**Pull request by Walker974**

### CODE REVIEW

**Review by PABLO-1610 — COMMENTED** [review]
We do not have any NPC object or anything related to it, i don't understand why are you creating this func :/

**Comment by Walker974** [comment]
I create this func to spawn npc with : 
 _NCS:createped(28, GetHashKey("s_m_y_ammucity_01"), {x = -812.74, y = -474.84, z =28.03}, 184.63)

**Comment by PABLO-1610** [comment]
Here, self refers to _NCS, so it can't be used.

**Comment by TheSpaceGamerV2** [comment]
Anyway should be better to create the ped server side

**Comment by Walker974** [comment]
> Anyway should be better to create the ped server side

Yes

**Comment by PABLO-1610** [comment]
As @TheSpaceGamerV2 said, we want to create peds server-side, so we'll look into it further :)

But thanks for the code proposal, you can also contribute on other aspect of the project.

**Pull request closed without merging**
