### PR TITLE
 🌟 : Create RichePresence API

### PR DESCRIPTION
**Pull request by utopi160**
image

### CODE REVIEW

**Comment by utopi160** [comment]
Ok but I find that passing a name is more intuitive,  no ?

**Comment by utopi160** [comment]
> Just pass the id into the constructor and do functions to add the rest, would be more efficient.

I changed the architecture but I don't see how adding the rest with functions would be more efficient...

**Review by CsokiHUN — APPROVED** [review]

**Comment by MoskalykA** [comment]
Hi, does the RichPresence have applications with multiple class calls? Because you put a list system but I don't find that required. And for the syntax, it has to be completely from the object so only enter the id in constructor in the class.

**Comment by utopi160** [comment]
> Hi, does the RichPresence have applications with multiple class calls? Because you put a list system but I don't find that required. And for the syntax, it has to be completely from the object so only enter the id in constructor in the class.

Like this ?
image

**Comment by utopi160** [comment]
And 

> Hi, does the RichPresence have applications with multiple class calls? Because you put a list system but I don't find that required. And for the syntax, it has to be completely from the object so only enter the id in constructor in the class.

And yes, the RichePresence will have multiple classes for example : 
image
image

**Comment by MoskalykA** [comment]
image
It's more logical to do it this way

**Comment by utopi160** [comment]
> It's more logical to do it this way

But to change logos, buttons and images. It will be easier to manage them, right?

**Comment by MoskalykA** [comment]
> But to change logos, buttons and images. It will be easier to manage them, right?

The idea of re-creating a class when it is not necessary is not the best idea at all

**Comment by utopi160** [comment]
> ng a class when it is not necessary is not the best idea at all

Mumm ok, my PR is a bad idea ?

**Comment by MoskalykA** [comment]
> Mumm ok, my PR is a bad idea ?

I only said that object-oriented is a good idea but that having multiple instances is a bad idea

**Comment by utopi160** [comment]
> > Mumm ok, my PR is a bad idea ?
> 
> I only said that object-oriented is a good idea but that having multiple instances is a bad idea

But how can I keep object-oriented and not have an instance of the class ?

**Comment by MoskalykA** [comment]
> But how can I keep object-oriented and not have an instance of the class ?

??? https://www.tutorialspoint.com/lua/lua_object_oriented.htm

**Pull request closed without merging**
