### PR TITLE
✨ Add HUD

### PR DESCRIPTION
**Pull request by nxtdv**
Adding the hud without the hunger or thirst system, there is just to adapt it. (see README.md)

### CODE REVIEW

**Comment by PABLO-1610** [comment]
Thanks for the contribution, i'll request a review from @Morow73 since i'm really bad at web dev 🤣

**Comment by Wisfakim** [comment]
I think using react is useless in this case and add more complexity in code.

**Comment by PABLO-1610** [comment]
> > I think using react is useless in this case and add more complexity in code.
> 
> Me too, for a HUD is useless, should be done with vanilla front-end

Yes indeed, it would be easier.

**Comment by MoskalykA** [comment]
> I think using react is useless in this case and add more complexity in code.

React is very useful for structuring your code and other things. If you find that React adds too much weight then use Preact. But if you're talking about how using React for a HUD is silly, I totally agree. (https://preactjs.com/)

**Comment by MoskalykA** [comment]
I propose to use React for the whole project and therefore to create a Provider for this. And of course to use Vite. (https://vitejs.dev/)

**Comment by PABLO-1610** [comment]
So, what we do guys ? @MoskalykA @nxtdv

**Comment by PABLO-1610** [comment]
@Morow73 any idea ?

**Comment by MoskalykA** [comment]
I propose to do the design part with React or Preact and then integrate the HUD later.

**Comment by PABLO-1610** [comment]
> I propose to do the design part with React or Preact and then integrate the HUD later.

Yeah good idea

**Pull request closed without merging**
